# Generated by Django 4.1.4 on 2022-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistuser',
            name='invited_users',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
