# Generated by Django 4.1.4 on 2022-12-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_waitlistuser_invited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistuser',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
